### ISSUE TITLE
Deactivate memes in survey answering process

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#54]
This feature which was disabled at some point, seems to be active again.
Upon providing a poor quality open anded answer, I meme popped up. The feedback provided "Awesome!" is not in line with AI assistant's evaluation.
EDIT: There are also emojis that appear after a scale answer is provided.

<img width="927" alt="image" src="https://github.com/gamification-survey-platform/client/assets/111450974/ce8a4af3-2409-476b-ace7-26a5f29f1ee0">

<img width="969" alt="image" src="https://github.com/gamification-survey-platform/client/assets/111450974/f2125ff4-dedf-40d3-8c88-4fd078210505">

**Comment by xinyuew3S2024** [comment]
hey @audrey-zhou,  I don't recall this functionality from my time on the project. Since you've previously worked extensively on this page, I thought you might have some insights for these memes? Could you help clarify if there was any meme-specific functionality added, or if there are any aspects of the UI that might be related to what the Professor is referring to? Any details you can provide would be really helpful.
